ADVANCED_CHALLENGES = [
    # ── Window Functions ────────────────────────────────────────────────────────
    {
        "id": "adv_001", "difficulty": "advanced", "category": "Window Functions",
        "title": "Rank Employees by Salary",
        "description": "Rank every employee by salary from highest (rank 1) to lowest. Show first_name, last_name, salary, and salary_rank. Use RANK() — ties get the same rank.",
        "hints": [
            "RANK() OVER (ORDER BY salary DESC) AS salary_rank",
            "Window functions don't collapse rows — every employee still appears.",
        ],
        "solution_sql": "SELECT first_name, last_name, salary, RANK() OVER (ORDER BY salary DESC) AS salary_rank FROM employees",
        "starter_sql": "SELECT first_name, last_name, salary,\n  RANK() OVER (ORDER BY salary DESC) AS salary_rank\nFROM employees",
        "validation": {"order_sensitive": False, "allow_extra_columns": False},
        "tables": ["employees"],
    },
    {
        "id": "adv_002", "difficulty": "advanced", "category": "Window Functions",
        "title": "Rank Within Department",
        "description": "Rank each employee by salary within their own department (highest salary = rank 1 in that dept). Show first_name, last_name, dept_id, salary, and dept_salary_rank.",
        "hints": [
            "RANK() OVER (PARTITION BY dept_id ORDER BY salary DESC)",
            "PARTITION BY resets the rank for each department.",
        ],
        "solution_sql": "SELECT first_name, last_name, dept_id, salary, RANK() OVER (PARTITION BY dept_id ORDER BY salary DESC) AS dept_salary_rank FROM employees",
        "starter_sql": "",
        "validation": {"order_sensitive": False, "allow_extra_columns": False},
        "tables": ["employees"],
    },
    {
        "id": "adv_003", "difficulty": "advanced", "category": "Window Functions",
        "title": "Row Number Per Customer",
        "description": "Number each customer's orders chronologically (1, 2, 3...). Show customer_id, order_id, order_date, and order_number.",
        "hints": [
            "ROW_NUMBER() OVER (PARTITION BY customer_id ORDER BY order_date) AS order_number",
        ],
        "solution_sql": "SELECT customer_id, id AS order_id, order_date, ROW_NUMBER() OVER (PARTITION BY customer_id ORDER BY order_date) AS order_number FROM orders",
        "starter_sql": "",
        "validation": {"order_sensitive": False, "allow_extra_columns": False},
        "tables": ["orders"],
    },
    {
        "id": "adv_004", "difficulty": "advanced", "category": "Window Functions",
        "title": "Running Total of Sales",
        "description": "For each sales rep (ordered by ytd_sales descending), calculate a running total of ytd_sales. Show employee_id, ytd_sales, and running_total.",
        "hints": [
            "SUM(ytd_sales) OVER (ORDER BY ytd_sales DESC ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW)",
            "This gives a cumulative sum as you move down the sorted list.",
        ],
        "solution_sql": "SELECT employee_id, ytd_sales, SUM(ytd_sales) OVER (ORDER BY ytd_sales DESC ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS running_total FROM sales_reps",
        "starter_sql": "",
        "validation": {"order_sensitive": True, "allow_extra_columns": False},
        "tables": ["sales_reps"],
    },
    {
        "id": "adv_005", "difficulty": "advanced", "category": "Window Functions",
        "title": "Previous Order Date (LAG)",
        "description": "For each order per customer, show the current order_date and the previous order_date (prev_order_date). Show customer_id, order_date, prev_order_date.",
        "hints": [
            "LAG(order_date) OVER (PARTITION BY customer_id ORDER BY order_date) AS prev_order_date",
            "LAG looks at the previous row in the window.",
        ],
        "solution_sql": "SELECT customer_id, order_date, LAG(order_date) OVER (PARTITION BY customer_id ORDER BY order_date) AS prev_order_date FROM orders",
        "starter_sql": "",
        "validation": {"order_sensitive": False, "allow_extra_columns": False},
        "tables": ["orders"],
    },
    {
        "id": "adv_006", "difficulty": "advanced", "category": "Window Functions",
        "title": "Dense Rank Products by Price",
        "description": "Assign a dense rank to each product by price (most expensive = rank 1). Show name, price, and price_rank. DENSE_RANK gives consecutive ranks with no gaps for ties.",
        "hints": [
            "DENSE_RANK() OVER (ORDER BY price DESC) AS price_rank",
            "Unlike RANK, DENSE_RANK doesn't skip numbers after a tie.",
        ],
        "solution_sql": "SELECT name, price, DENSE_RANK() OVER (ORDER BY price DESC) AS price_rank FROM products",
        "starter_sql": "",
        "validation": {"order_sensitive": False, "allow_extra_columns": False},
        "tables": ["products"],
    },
    {
        "id": "adv_007", "difficulty": "advanced", "category": "Window Functions",
        "title": "Salary vs Department Average",
        "description": "For each employee, show first_name, last_name, salary, and the average salary of their department as dept_avg_salary.",
        "hints": [
            "AVG(salary) OVER (PARTITION BY dept_id) AS dept_avg_salary",
            "Window functions can compute group stats without collapsing rows.",
        ],
        "solution_sql": "SELECT first_name, last_name, salary, AVG(salary) OVER (PARTITION BY dept_id) AS dept_avg_salary FROM employees",
        "starter_sql": "",
        "validation": {"order_sensitive": False, "allow_extra_columns": False},
        "tables": ["employees"],
    },
    # ── CTEs ────────────────────────────────────────────────────────────────────
    {
        "id": "adv_008", "difficulty": "advanced", "category": "CTEs",
        "title": "Top Earner Per Department (CTE)",
        "description": "Using a CTE, find the highest salary in each department, then return the employee(s) whose salary matches that maximum. Show dept_id, first_name, last_name, and salary.",
        "hints": [
            "WITH dept_max AS (SELECT dept_id, MAX(salary) AS max_salary FROM employees GROUP BY dept_id)",
            "Then JOIN employees to dept_max on dept_id and salary = max_salary.",
        ],
        "solution_sql": "WITH dept_max AS (SELECT dept_id, MAX(salary) AS max_salary FROM employees GROUP BY dept_id) SELECT e.dept_id, e.first_name, e.last_name, e.salary FROM employees e JOIN dept_max dm ON e.dept_id = dm.dept_id AND e.salary = dm.max_salary",
        "starter_sql": "WITH dept_max AS (\n  SELECT dept_id, MAX(salary) AS max_salary\n  FROM employees\n  GROUP BY dept_id\n)\nSELECT e.dept_id, e.first_name, e.last_name, e.salary\nFROM employees e\nJOIN dept_max dm ON",
        "validation": {"order_sensitive": False, "allow_extra_columns": False},
        "tables": ["employees"],
    },
    {
        "id": "adv_009", "difficulty": "advanced", "category": "CTEs",
        "title": "Customers With Above-Average Orders (CTE)",
        "description": "Using a CTE, first calculate the average number of orders per customer, then find customers who have placed more orders than that average. Show customer_id and order_count.",
        "hints": [
            "CTE 1: count orders per customer.",
            "CTE 2 or subquery: compute AVG of those counts.",
            "Final query: filter where order_count > avg.",
        ],
        "solution_sql": "WITH order_counts AS (SELECT customer_id, COUNT(*) AS order_count FROM orders GROUP BY customer_id), avg_orders AS (SELECT AVG(order_count) AS avg_count FROM order_counts) SELECT oc.customer_id, oc.order_count FROM order_counts oc, avg_orders WHERE oc.order_count > avg_orders.avg_count",
        "starter_sql": "",
        "validation": {"order_sensitive": False, "allow_extra_columns": False},
        "tables": ["orders"],
    },
    {
        "id": "adv_010", "difficulty": "advanced", "category": "CTEs",
        "title": "Revenue Per Product CTE",
        "description": "Using a CTE, calculate total revenue per product (SUM of quantity * unit_price from order_items), then show the top 10 products by revenue along with the product name.",
        "hints": [
            "CTE: SELECT product_id, SUM(quantity * unit_price) AS revenue FROM order_items GROUP BY product_id",
            "JOIN the CTE to products to get the name.",
        ],
        "solution_sql": "WITH product_revenue AS (SELECT product_id, SUM(quantity * unit_price) AS revenue FROM order_items GROUP BY product_id) SELECT p.name, pr.revenue FROM product_revenue pr JOIN products p ON pr.product_id = p.id ORDER BY pr.revenue DESC LIMIT 10",
        "starter_sql": "",
        "validation": {"order_sensitive": True, "allow_extra_columns": False},
        "tables": ["order_items", "products"],
    },
    {
        "id": "adv_011", "difficulty": "advanced", "category": "CTEs",
        "title": "Multi-Step Analysis CTE",
        "description": "Using two CTEs: first find each customer's total spend, then classify them as 'VIP' (>2000), 'Regular' (500-2000), or 'Casual' (<500). Show customer_id, total_spend, and customer_tier.",
        "hints": [
            "CTE 1: SUM(total_amount) per customer_id.",
            "CTE 2 or main query: CASE WHEN on the total_spend.",
        ],
        "solution_sql": "WITH customer_spend AS (SELECT customer_id, SUM(total_amount) AS total_spend FROM orders GROUP BY customer_id) SELECT customer_id, total_spend, CASE WHEN total_spend > 2000 THEN 'VIP' WHEN total_spend >= 500 THEN 'Regular' ELSE 'Casual' END AS customer_tier FROM customer_spend",
        "starter_sql": "",
        "validation": {"order_sensitive": False, "allow_extra_columns": False},
        "tables": ["orders"],
    },
    # ── Self Joins ──────────────────────────────────────────────────────────────
    {
        "id": "adv_012", "difficulty": "advanced", "category": "Self Joins",
        "title": "Employee and Their Manager",
        "description": "For each employee who has a manager, show the employee's full name and their manager's full name. Use a self-join on the employees table.",
        "hints": [
            "Alias the employees table twice: e (employee) and m (manager).",
            "JOIN employees m ON e.manager_id = m.id",
            "WHERE e.manager_id IS NOT NULL to skip employees without managers.",
        ],
        "solution_sql": "SELECT e.first_name || ' ' || e.last_name AS employee_name, m.first_name || ' ' || m.last_name AS manager_name FROM employees e JOIN employees m ON e.manager_id = m.id",
        "starter_sql": "SELECT e.first_name || ' ' || e.last_name AS employee_name,\n       m.first_name || ' ' || m.last_name AS manager_name\nFROM employees e\nJOIN employees m ON",
        "validation": {"order_sensitive": False, "allow_extra_columns": False},
        "tables": ["employees"],
    },
    {
        "id": "adv_013", "difficulty": "advanced", "category": "Self Joins",
        "title": "Manager Headcount",
        "description": "Find each manager and count how many direct reports they have. Show manager_id and direct_report_count, sorted by direct_report_count descending.",
        "hints": [
            "GROUP BY manager_id, COUNT(*) on the employees table.",
            "Filter WHERE manager_id IS NOT NULL to exclude non-managers.",
        ],
        "solution_sql": "SELECT manager_id, COUNT(*) AS direct_report_count FROM employees WHERE manager_id IS NOT NULL GROUP BY manager_id ORDER BY direct_report_count DESC",
        "starter_sql": "",
        "validation": {"order_sensitive": True, "allow_extra_columns": False},
        "tables": ["employees"],
    },
    # ── UNION / INTERSECT / EXCEPT ─────────────────────────────────────────────
    {
        "id": "adv_014", "difficulty": "advanced", "category": "Set Operations",
        "title": "All Names (Employees + Customers)",
        "description": "Retrieve a combined list of all first names from both the employees and customers tables. Use UNION to eliminate duplicates. Label the column 'name'.",
        "hints": [
            "UNION combines two SELECT results and removes duplicates.",
            "Both SELECTs must have the same number of columns.",
        ],
        "solution_sql": "SELECT first_name AS name FROM employees UNION SELECT first_name AS name FROM customers",
        "starter_sql": "SELECT first_name AS name FROM employees\nUNION\n",
        "validation": {"order_sensitive": False, "allow_extra_columns": False},
        "tables": ["employees", "customers"],
    },
    {
        "id": "adv_015", "difficulty": "advanced", "category": "Set Operations",
        "title": "States in Both Employees and Customers",
        "description": "Find all distinct locations that appear in both departments.location and customers.city. This is the intersection — use INTERSECT.",
        "hints": [
            "INTERSECT returns only values found in both result sets.",
            "SELECT location FROM departments INTERSECT SELECT city FROM customers",
        ],
        "solution_sql": "SELECT location FROM departments INTERSECT SELECT city FROM customers",
        "starter_sql": "",
        "validation": {"order_sensitive": False, "allow_extra_columns": False},
        "tables": ["departments", "customers"],
    },
    {
        "id": "adv_016", "difficulty": "advanced", "category": "Set Operations",
        "title": "Products Never Ordered",
        "description": "Find all product ids that have never appeared in order_items, using EXCEPT.",
        "hints": [
            "SELECT id FROM products EXCEPT SELECT product_id FROM order_items",
        ],
        "solution_sql": "SELECT id FROM products EXCEPT SELECT product_id FROM order_items",
        "starter_sql": "",
        "validation": {"order_sensitive": False, "allow_extra_columns": False},
        "tables": ["products", "order_items"],
    },
    # ── EXISTS / NOT EXISTS ────────────────────────────────────────────────────
    {
        "id": "adv_017", "difficulty": "advanced", "category": "EXISTS",
        "title": "Customers Who Have Ordered (EXISTS)",
        "description": "Find customers who have placed at least one order. Use EXISTS instead of IN. Show first_name and last_name.",
        "hints": [
            "WHERE EXISTS (SELECT 1 FROM orders WHERE orders.customer_id = customers.id)",
            "EXISTS returns true if the subquery produces any row.",
        ],
        "solution_sql": "SELECT first_name, last_name FROM customers WHERE EXISTS (SELECT 1 FROM orders WHERE orders.customer_id = customers.id)",
        "starter_sql": "SELECT first_name, last_name FROM customers\nWHERE EXISTS (SELECT 1 FROM orders WHERE",
        "validation": {"order_sensitive": False, "allow_extra_columns": False},
        "tables": ["customers", "orders"],
    },
    {
        "id": "adv_018", "difficulty": "advanced", "category": "EXISTS",
        "title": "Products With No Orders (NOT EXISTS)",
        "description": "Find all products that have never been included in any order. Show product name. Use NOT EXISTS.",
        "hints": [
            "WHERE NOT EXISTS (SELECT 1 FROM order_items WHERE order_items.product_id = products.id)",
        ],
        "solution_sql": "SELECT name FROM products WHERE NOT EXISTS (SELECT 1 FROM order_items WHERE order_items.product_id = products.id)",
        "starter_sql": "",
        "validation": {"order_sensitive": False, "allow_extra_columns": False},
        "tables": ["products", "order_items"],
    },
    # ── Correlated Subqueries ───────────────────────────────────────────────────
    {
        "id": "adv_019", "difficulty": "advanced", "category": "Correlated Subqueries",
        "title": "Employees Above Their Dept Average",
        "description": "Find employees whose salary is higher than the average salary of their own department. Show first_name, last_name, dept_id, salary.",
        "hints": [
            "Use a correlated subquery: WHERE salary > (SELECT AVG(salary) FROM employees e2 WHERE e2.dept_id = e.dept_id)",
            "The inner query references the outer query's row with e.dept_id.",
        ],
        "solution_sql": "SELECT first_name, last_name, dept_id, salary FROM employees e WHERE salary > (SELECT AVG(salary) FROM employees e2 WHERE e2.dept_id = e.dept_id)",
        "starter_sql": "SELECT first_name, last_name, dept_id, salary\nFROM employees e\nWHERE salary > (SELECT AVG(salary) FROM employees e2 WHERE",
        "validation": {"order_sensitive": False, "allow_extra_columns": False},
        "tables": ["employees"],
    },
    {
        "id": "adv_020", "difficulty": "advanced", "category": "Correlated Subqueries",
        "title": "Most Recent Order Per Customer",
        "description": "For each customer, retrieve their most recent order (the one with the latest order_date). Show customer_id, id as order_id, and order_date.",
        "hints": [
            "WHERE order_date = (SELECT MAX(order_date) FROM orders o2 WHERE o2.customer_id = o.customer_id)",
        ],
        "solution_sql": "SELECT customer_id, id AS order_id, order_date FROM orders o WHERE order_date = (SELECT MAX(order_date) FROM orders o2 WHERE o2.customer_id = o.customer_id)",
        "starter_sql": "",
        "validation": {"order_sensitive": False, "allow_extra_columns": False},
        "tables": ["orders"],
    },
    # ── Top-N Per Group ─────────────────────────────────────────────────────────
    {
        "id": "adv_021", "difficulty": "advanced", "category": "Window Functions",
        "title": "Top 2 Earners Per Department",
        "description": "Find the top 2 highest-paid employees in each department. Show dept_id, first_name, last_name, salary.",
        "hints": [
            "Use ROW_NUMBER() OVER (PARTITION BY dept_id ORDER BY salary DESC) AS rn in a subquery or CTE.",
            "Then filter WHERE rn <= 2 in the outer query.",
        ],
        "solution_sql": "WITH ranked AS (SELECT dept_id, first_name, last_name, salary, ROW_NUMBER() OVER (PARTITION BY dept_id ORDER BY salary DESC) AS rn FROM employees) SELECT dept_id, first_name, last_name, salary FROM ranked WHERE rn <= 2",
        "starter_sql": "WITH ranked AS (\n  SELECT dept_id, first_name, last_name, salary,\n         ROW_NUMBER() OVER (PARTITION BY dept_id ORDER BY salary DESC) AS rn\n  FROM employees\n)\nSELECT dept_id, first_name, last_name, salary\nFROM ranked\nWHERE",
        "validation": {"order_sensitive": False, "allow_extra_columns": False},
        "tables": ["employees"],
    },
    {
        "id": "adv_022", "difficulty": "advanced", "category": "Window Functions",
        "title": "Top 3 Products by Revenue Per Category",
        "description": "Find the top 3 products by total revenue (quantity * unit_price from order_items) within each product category. Show category, product name, and total_revenue.",
        "hints": [
            "CTE 1: calculate revenue per product from order_items.",
            "CTE 2: JOIN to products to get category.",
            "Use ROW_NUMBER() OVER (PARTITION BY category ORDER BY total_revenue DESC) and filter rn <= 3.",
        ],
        "solution_sql": "WITH product_rev AS (SELECT product_id, SUM(quantity * unit_price) AS total_revenue FROM order_items GROUP BY product_id), ranked AS (SELECT p.category, p.name, pr.total_revenue, ROW_NUMBER() OVER (PARTITION BY p.category ORDER BY pr.total_revenue DESC) AS rn FROM product_rev pr JOIN products p ON pr.product_id = p.id) SELECT category, name, total_revenue FROM ranked WHERE rn <= 3",
        "starter_sql": "",
        "validation": {"order_sensitive": False, "allow_extra_columns": False},
        "tables": ["order_items", "products"],
    },
    {
        "id": "adv_023", "difficulty": "advanced", "category": "Window Functions",
        "title": "LEAD — Next Order Date",
        "description": "For each order per customer, show the next order_date (next_order_date). Show customer_id, order_date, and next_order_date.",
        "hints": [
            "LEAD(order_date) OVER (PARTITION BY customer_id ORDER BY order_date) AS next_order_date",
            "LEAD looks at the next row in the window.",
        ],
        "solution_sql": "SELECT customer_id, order_date, LEAD(order_date) OVER (PARTITION BY customer_id ORDER BY order_date) AS next_order_date FROM orders",
        "starter_sql": "",
        "validation": {"order_sensitive": False, "allow_extra_columns": False},
        "tables": ["orders"],
    },
    {
        "id": "adv_024", "difficulty": "advanced", "category": "CTEs",
        "title": "Recursive-Style Hierarchy",
        "description": "Using CTEs (non-recursive), find all employees who report directly to manager_id = 1, and show their full names.",
        "hints": [
            "WITH direct_reports AS (SELECT * FROM employees WHERE manager_id = 1)",
            "Then SELECT from the CTE.",
        ],
        "solution_sql": "WITH direct_reports AS (SELECT * FROM employees WHERE manager_id = 1) SELECT first_name || ' ' || last_name AS full_name FROM direct_reports",
        "starter_sql": "",
        "validation": {"order_sensitive": False, "allow_extra_columns": False},
        "tables": ["employees"],
    },
    {
        "id": "adv_025", "difficulty": "advanced", "category": "Correlated Subqueries",
        "title": "Orders Above Customer Average",
        "description": "Find orders where total_amount is above that customer's own average order amount. Show customer_id, order id, and total_amount.",
        "hints": [
            "WHERE total_amount > (SELECT AVG(total_amount) FROM orders o2 WHERE o2.customer_id = o.customer_id)",
        ],
        "solution_sql": "SELECT customer_id, id AS order_id, total_amount FROM orders o WHERE total_amount > (SELECT AVG(total_amount) FROM orders o2 WHERE o2.customer_id = o.customer_id)",
        "starter_sql": "",
        "validation": {"order_sensitive": False, "allow_extra_columns": False},
        "tables": ["orders"],
    },
    {
        "id": "adv_026", "difficulty": "advanced", "category": "Window Functions",
        "title": "Percentile Rank of Salary",
        "description": "For each employee, calculate their salary percentile rank (as a value 0.0 to 1.0) using PERCENT_RANK(). Show first_name, last_name, salary, and pct_rank.",
        "hints": [
            "PERCENT_RANK() OVER (ORDER BY salary) AS pct_rank",
            "0.0 = lowest salary, 1.0 = highest.",
        ],
        "solution_sql": "SELECT first_name, last_name, salary, PERCENT_RANK() OVER (ORDER BY salary) AS pct_rank FROM employees",
        "starter_sql": "",
        "validation": {"order_sensitive": False, "allow_extra_columns": False},
        "tables": ["employees"],
    },
    {
        "id": "adv_027", "difficulty": "advanced", "category": "CTEs",
        "title": "First Order of Each Customer",
        "description": "Using a CTE with ROW_NUMBER, find the very first order placed by each customer. Show customer_id, order_id, and order_date.",
        "hints": [
            "CTE: ROW_NUMBER() OVER (PARTITION BY customer_id ORDER BY order_date) AS rn",
            "Filter WHERE rn = 1 in the outer query.",
        ],
        "solution_sql": "WITH numbered AS (SELECT customer_id, id AS order_id, order_date, ROW_NUMBER() OVER (PARTITION BY customer_id ORDER BY order_date) AS rn FROM orders) SELECT customer_id, order_id, order_date FROM numbered WHERE rn = 1",
        "starter_sql": "",
        "validation": {"order_sensitive": False, "allow_extra_columns": False},
        "tables": ["orders"],
    },
    {
        "id": "adv_028", "difficulty": "advanced", "category": "Set Operations",
        "title": "UNION ALL (Preserve Duplicates)",
        "description": "List all first names from employees, followed by all first names from customers — keep ALL duplicates (do not remove them). Label the column 'first_name'. Show the total count of rows at the end using a wrapper query — just return all names with UNION ALL.",
        "hints": [
            "UNION ALL keeps duplicates, unlike UNION.",
        ],
        "solution_sql": "SELECT first_name FROM employees UNION ALL SELECT first_name FROM customers",
        "starter_sql": "",
        "validation": {"order_sensitive": False, "allow_extra_columns": False},
        "tables": ["employees", "customers"],
    },
    {
        "id": "adv_029", "difficulty": "advanced", "category": "Window Functions",
        "title": "Moving Average of Order Amounts",
        "description": "Calculate a 3-row moving average of total_amount for orders sorted by order_date. Show order_date, total_amount, and moving_avg.",
        "hints": [
            "AVG(total_amount) OVER (ORDER BY order_date ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) AS moving_avg",
        ],
        "solution_sql": "SELECT order_date, total_amount, AVG(total_amount) OVER (ORDER BY order_date ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) AS moving_avg FROM orders",
        "starter_sql": "",
        "validation": {"order_sensitive": False, "allow_extra_columns": False},
        "tables": ["orders"],
    },
    {
        "id": "adv_030", "difficulty": "advanced", "category": "EXISTS",
        "title": "Departments With Active Employees",
        "description": "Find departments that have at least one active employee (is_active = 1). Show department name. Use EXISTS.",
        "hints": [
            "WHERE EXISTS (SELECT 1 FROM employees WHERE employees.dept_id = departments.id AND is_active = 1)",
        ],
        "solution_sql": "SELECT name FROM departments WHERE EXISTS (SELECT 1 FROM employees WHERE employees.dept_id = departments.id AND is_active = 1)",
        "starter_sql": "",
        "validation": {"order_sensitive": False, "allow_extra_columns": False},
        "tables": ["departments", "employees"],
    },
]
