BEGINNER_CHALLENGES = [
    # ── SELECT basics ──────────────────────────────────────────────────────────
    {
        "id": "beg_001", "difficulty": "beginner", "category": "SELECT",
        "title": "All Employees",
        "description": "Retrieve every row and every column from the employees table.",
        "hints": ["Use SELECT * to select all columns.", "FROM tells SQL which table to look in."],
        "solution_sql": "SELECT * FROM employees",
        "starter_sql": "SELECT\nFROM",
        "validation": {"order_sensitive": False, "allow_extra_columns": False},
        "tables": ["employees"],
    },
    {
        "id": "beg_002", "difficulty": "beginner", "category": "SELECT",
        "title": "Employee Names Only",
        "description": "Retrieve only the first_name and last_name columns from the employees table.",
        "hints": ["List column names separated by commas after SELECT."],
        "solution_sql": "SELECT first_name, last_name FROM employees",
        "starter_sql": "SELECT\nFROM employees",
        "validation": {"order_sensitive": False, "allow_extra_columns": False},
        "tables": ["employees"],
    },
    {
        "id": "beg_003", "difficulty": "beginner", "category": "SELECT",
        "title": "All Products",
        "description": "Retrieve every row and column from the products table.",
        "hints": ["SELECT * returns all columns."],
        "solution_sql": "SELECT * FROM products",
        "starter_sql": "",
        "validation": {"order_sensitive": False, "allow_extra_columns": False},
        "tables": ["products"],
    },
    {
        "id": "beg_004", "difficulty": "beginner", "category": "SELECT",
        "title": "Customer Contact Info",
        "description": "Retrieve the first_name, last_name, and email of all customers.",
        "hints": ["Select three specific columns from the customers table."],
        "solution_sql": "SELECT first_name, last_name, email FROM customers",
        "starter_sql": "",
        "validation": {"order_sensitive": False, "allow_extra_columns": False},
        "tables": ["customers"],
    },
    {
        "id": "beg_005", "difficulty": "beginner", "category": "SELECT",
        "title": "All Departments",
        "description": "Retrieve every column from the departments table.",
        "hints": ["You can use * to get every column."],
        "solution_sql": "SELECT * FROM departments",
        "starter_sql": "",
        "validation": {"order_sensitive": False, "allow_extra_columns": False},
        "tables": ["departments"],
    },
    # ── DISTINCT ───────────────────────────────────────────────────────────────
    {
        "id": "beg_006", "difficulty": "beginner", "category": "SELECT",
        "title": "Unique Product Categories",
        "description": "Retrieve a list of all unique product categories from the products table. No duplicates.",
        "hints": ["DISTINCT removes duplicate values.", "Place DISTINCT right after SELECT."],
        "solution_sql": "SELECT DISTINCT category FROM products",
        "starter_sql": "SELECT\nFROM products",
        "validation": {"order_sensitive": False, "allow_extra_columns": False},
        "tables": ["products"],
    },
    {
        "id": "beg_007", "difficulty": "beginner", "category": "SELECT",
        "title": "Unique Order Statuses",
        "description": "List every distinct order status that appears in the orders table.",
        "hints": ["Use DISTINCT on the status column."],
        "solution_sql": "SELECT DISTINCT status FROM orders",
        "starter_sql": "",
        "validation": {"order_sensitive": False, "allow_extra_columns": False},
        "tables": ["orders"],
    },
    {
        "id": "beg_008", "difficulty": "beginner", "category": "SELECT",
        "title": "Unique States",
        "description": "List every state that at least one customer lives in. No duplicates.",
        "hints": ["DISTINCT works on any column."],
        "solution_sql": "SELECT DISTINCT state FROM customers",
        "starter_sql": "",
        "validation": {"order_sensitive": False, "allow_extra_columns": False},
        "tables": ["customers"],
    },
    # ── LIMIT ──────────────────────────────────────────────────────────────────
    {
        "id": "beg_009", "difficulty": "beginner", "category": "LIMIT",
        "title": "First 10 Customers",
        "description": "Retrieve the first 10 rows from the customers table.",
        "hints": ["LIMIT comes at the very end of a query.", "LIMIT 10 returns at most 10 rows."],
        "solution_sql": "SELECT * FROM customers LIMIT 10",
        "starter_sql": "SELECT * FROM customers\n",
        "validation": {"order_sensitive": False, "allow_extra_columns": False},
        "tables": ["customers"],
    },
    {
        "id": "beg_010", "difficulty": "beginner", "category": "LIMIT",
        "title": "Peek at Orders",
        "description": "Retrieve only 5 rows from the orders table to preview its structure.",
        "hints": ["Use LIMIT 5 at the end of your query."],
        "solution_sql": "SELECT * FROM orders LIMIT 5",
        "starter_sql": "",
        "validation": {"order_sensitive": False, "allow_extra_columns": False},
        "tables": ["orders"],
    },
    {
        "id": "beg_011", "difficulty": "beginner", "category": "LIMIT",
        "title": "Skip and Take",
        "description": "Retrieve employees 11 through 20 (skip the first 10, then take the next 10).",
        "hints": ["OFFSET tells SQL how many rows to skip.", "Use LIMIT 10 OFFSET 10."],
        "solution_sql": "SELECT * FROM employees LIMIT 10 OFFSET 10",
        "starter_sql": "",
        "validation": {"order_sensitive": False, "allow_extra_columns": False},
        "tables": ["employees"],
    },
    # ── WHERE ──────────────────────────────────────────────────────────────────
    {
        "id": "beg_012", "difficulty": "beginner", "category": "WHERE",
        "title": "Active Employees",
        "description": "Retrieve all employees where is_active equals 1.",
        "hints": ["WHERE filters rows that match a condition.", "Use = to compare values."],
        "solution_sql": "SELECT * FROM employees WHERE is_active = 1",
        "starter_sql": "SELECT * FROM employees\nWHERE",
        "validation": {"order_sensitive": False, "allow_extra_columns": False},
        "tables": ["employees"],
    },
    {
        "id": "beg_013", "difficulty": "beginner", "category": "WHERE",
        "title": "Delivered Orders",
        "description": "Retrieve all orders where the status is 'delivered'.",
        "hints": ["Text values in SQL need quotes: WHERE status = 'delivered'"],
        "solution_sql": "SELECT * FROM orders WHERE status = 'delivered'",
        "starter_sql": "",
        "validation": {"order_sensitive": False, "allow_extra_columns": False},
        "tables": ["orders"],
    },
    {
        "id": "beg_014", "difficulty": "beginner", "category": "WHERE",
        "title": "High Earners",
        "description": "Find all employees with a salary greater than 100000.",
        "hints": ["Use the > operator for 'greater than'."],
        "solution_sql": "SELECT * FROM employees WHERE salary > 100000",
        "starter_sql": "",
        "validation": {"order_sensitive": False, "allow_extra_columns": False},
        "tables": ["employees"],
    },
    {
        "id": "beg_015", "difficulty": "beginner", "category": "WHERE",
        "title": "Affordable Products",
        "description": "Find all products with a price less than or equal to 50.",
        "hints": ["Use <= for 'less than or equal to'."],
        "solution_sql": "SELECT * FROM products WHERE price <= 50",
        "starter_sql": "",
        "validation": {"order_sensitive": False, "allow_extra_columns": False},
        "tables": ["products"],
    },
    {
        "id": "beg_016", "difficulty": "beginner", "category": "WHERE",
        "title": "Not Cancelled",
        "description": "Find all orders that are NOT in 'cancelled' status.",
        "hints": ["Use != or <> to mean 'not equal to'."],
        "solution_sql": "SELECT * FROM orders WHERE status != 'cancelled'",
        "starter_sql": "",
        "validation": {"order_sensitive": False, "allow_extra_columns": False},
        "tables": ["orders"],
    },
    {
        "id": "beg_017", "difficulty": "beginner", "category": "WHERE",
        "title": "Electronics Products",
        "description": "Find all products in the 'Electronics' category.",
        "hints": ["Match category = 'Electronics' exactly (case matters)."],
        "solution_sql": "SELECT * FROM products WHERE category = 'Electronics'",
        "starter_sql": "",
        "validation": {"order_sensitive": False, "allow_extra_columns": False},
        "tables": ["products"],
    },
    {
        "id": "beg_018", "difficulty": "beginner", "category": "WHERE",
        "title": "Department 1 Employees",
        "description": "Find all employees in department 1 (dept_id = 1).",
        "hints": ["dept_id is a number, no quotes needed."],
        "solution_sql": "SELECT * FROM employees WHERE dept_id = 1",
        "starter_sql": "",
        "validation": {"order_sensitive": False, "allow_extra_columns": False},
        "tables": ["employees"],
    },
    # ── WHERE AND/OR/NOT ───────────────────────────────────────────────────────
    {
        "id": "beg_019", "difficulty": "beginner", "category": "WHERE",
        "title": "Active High Earners",
        "description": "Find employees who are active (is_active = 1) AND earn more than 80000.",
        "hints": ["Use AND to combine two conditions — both must be true."],
        "solution_sql": "SELECT * FROM employees WHERE is_active = 1 AND salary > 80000",
        "starter_sql": "",
        "validation": {"order_sensitive": False, "allow_extra_columns": False},
        "tables": ["employees"],
    },
    {
        "id": "beg_020", "difficulty": "beginner", "category": "WHERE",
        "title": "Shipped or Delivered",
        "description": "Find orders that have a status of either 'shipped' or 'delivered'.",
        "hints": ["Use OR when either condition is acceptable."],
        "solution_sql": "SELECT * FROM orders WHERE status = 'shipped' OR status = 'delivered'",
        "starter_sql": "",
        "validation": {"order_sensitive": False, "allow_extra_columns": False},
        "tables": ["orders"],
    },
    {
        "id": "beg_021", "difficulty": "beginner", "category": "WHERE",
        "title": "Mid-Range Salary",
        "description": "Find employees with a salary between 50000 and 75000 (inclusive).",
        "hints": ["Use BETWEEN ... AND ... for range checks.", "BETWEEN is inclusive of both endpoints."],
        "solution_sql": "SELECT * FROM employees WHERE salary BETWEEN 50000 AND 75000",
        "starter_sql": "",
        "validation": {"order_sensitive": False, "allow_extra_columns": False},
        "tables": ["employees"],
    },
    {
        "id": "beg_022", "difficulty": "beginner", "category": "WHERE",
        "title": "Customers in TX or CA",
        "description": "Find customers who live in the state 'TX' or 'CA'.",
        "hints": ["OR works here, but IN is cleaner: WHERE state IN ('TX', 'CA')"],
        "solution_sql": "SELECT * FROM customers WHERE state IN ('TX', 'CA')",
        "starter_sql": "",
        "validation": {"order_sensitive": False, "allow_extra_columns": False},
        "tables": ["customers"],
    },
    {
        "id": "beg_023", "difficulty": "beginner", "category": "WHERE",
        "title": "Employees Without Managers",
        "description": "Find all employees where manager_id is NULL (they have no manager).",
        "hints": ["NULL means 'no value'. Use IS NULL to check for it.", "Don't use = NULL — that won't work in SQL."],
        "solution_sql": "SELECT * FROM employees WHERE manager_id IS NULL",
        "starter_sql": "",
        "validation": {"order_sensitive": False, "allow_extra_columns": False},
        "tables": ["employees"],
    },
    {
        "id": "beg_024", "difficulty": "beginner", "category": "WHERE",
        "title": "Employees With Managers",
        "description": "Find all employees who DO have a manager (manager_id is not null).",
        "hints": ["Use IS NOT NULL to check that a value exists."],
        "solution_sql": "SELECT * FROM employees WHERE manager_id IS NOT NULL",
        "starter_sql": "",
        "validation": {"order_sensitive": False, "allow_extra_columns": False},
        "tables": ["employees"],
    },
    # ── LIKE ───────────────────────────────────────────────────────────────────
    {
        "id": "beg_025", "difficulty": "beginner", "category": "WHERE",
        "title": "Customers Named 'J'",
        "description": "Find all customers whose first_name starts with the letter 'J'.",
        "hints": ["LIKE uses % as a wildcard for any characters.", "WHERE first_name LIKE 'J%' matches any name starting with J."],
        "solution_sql": "SELECT * FROM customers WHERE first_name LIKE 'J%'",
        "starter_sql": "",
        "validation": {"order_sensitive": False, "allow_extra_columns": False},
        "tables": ["customers"],
    },
    {
        "id": "beg_026", "difficulty": "beginner", "category": "WHERE",
        "title": "Gmail Customers",
        "description": "Find all customers whose email address ends with '@gmail.com'.",
        "hints": ["Use LIKE '%@gmail.com' — the % goes at the beginning for 'ends with'."],
        "solution_sql": "SELECT * FROM customers WHERE email LIKE '%@gmail.com'",
        "starter_sql": "",
        "validation": {"order_sensitive": False, "allow_extra_columns": False},
        "tables": ["customers"],
    },
    {
        "id": "beg_027", "difficulty": "beginner", "category": "WHERE",
        "title": "Products Containing 'Pro'",
        "description": "Find all products whose name contains the word 'pro' (case insensitive).",
        "hints": ["Use LIKE '%pro%' — % on both sides means 'contains'.", "LIKE in SQLite is case-insensitive for ASCII letters."],
        "solution_sql": "SELECT * FROM products WHERE name LIKE '%pro%'",
        "starter_sql": "",
        "validation": {"order_sensitive": False, "allow_extra_columns": False},
        "tables": ["products"],
    },
    # ── IN / NOT IN ────────────────────────────────────────────────────────────
    {
        "id": "beg_028", "difficulty": "beginner", "category": "WHERE",
        "title": "Multiple Departments",
        "description": "Find employees who work in department 2, 5, or 7.",
        "hints": ["IN (...) lets you match multiple values cleanly."],
        "solution_sql": "SELECT * FROM employees WHERE dept_id IN (2, 5, 7)",
        "starter_sql": "",
        "validation": {"order_sensitive": False, "allow_extra_columns": False},
        "tables": ["employees"],
    },
    {
        "id": "beg_029", "difficulty": "beginner", "category": "WHERE",
        "title": "Exclude Certain Statuses",
        "description": "Find orders that are NOT 'cancelled' or 'pending'.",
        "hints": ["NOT IN excludes the listed values."],
        "solution_sql": "SELECT * FROM orders WHERE status NOT IN ('cancelled', 'pending')",
        "starter_sql": "",
        "validation": {"order_sensitive": False, "allow_extra_columns": False},
        "tables": ["orders"],
    },
    # ── ORDER BY ───────────────────────────────────────────────────────────────
    {
        "id": "beg_030", "difficulty": "beginner", "category": "ORDER BY",
        "title": "Employees by Salary (High to Low)",
        "description": "List all employees sorted by salary from highest to lowest.",
        "hints": ["ORDER BY col DESC sorts highest first.", "Default is ASC (ascending)."],
        "solution_sql": "SELECT * FROM employees ORDER BY salary DESC",
        "starter_sql": "SELECT * FROM employees\nORDER BY",
        "validation": {"order_sensitive": True, "allow_extra_columns": False},
        "tables": ["employees"],
    },
    {
        "id": "beg_031", "difficulty": "beginner", "category": "ORDER BY",
        "title": "Customers Alphabetically",
        "description": "List all customers sorted by last_name A to Z, then first_name A to Z.",
        "hints": ["You can ORDER BY multiple columns separated by commas.", "The second column is the tiebreaker."],
        "solution_sql": "SELECT * FROM customers ORDER BY last_name ASC, first_name ASC",
        "starter_sql": "",
        "validation": {"order_sensitive": True, "allow_extra_columns": False},
        "tables": ["customers"],
    },
    {
        "id": "beg_032", "difficulty": "beginner", "category": "ORDER BY",
        "title": "Newest Orders First",
        "description": "List all orders sorted by order_date from newest to oldest.",
        "hints": ["Dates stored as text ('YYYY-MM-DD') sort correctly with ORDER BY.", "Use DESC for newest first."],
        "solution_sql": "SELECT * FROM orders ORDER BY order_date DESC",
        "starter_sql": "",
        "validation": {"order_sensitive": True, "allow_extra_columns": False},
        "tables": ["orders"],
    },
    {
        "id": "beg_033", "difficulty": "beginner", "category": "ORDER BY",
        "title": "Cheapest Products First",
        "description": "List all products sorted by price from cheapest to most expensive.",
        "hints": ["ASC is the default order — lowest value first."],
        "solution_sql": "SELECT * FROM products ORDER BY price ASC",
        "starter_sql": "",
        "validation": {"order_sensitive": True, "allow_extra_columns": False},
        "tables": ["products"],
    },
    # ── Combining WHERE + ORDER BY + LIMIT ─────────────────────────────────────
    {
        "id": "beg_034", "difficulty": "beginner", "category": "WHERE",
        "title": "Top 5 Highest-Paid Active Employees",
        "description": "Find the 5 highest-paid employees who are currently active (is_active = 1).",
        "hints": ["Combine WHERE, ORDER BY, and LIMIT.", "Order: WHERE → ORDER BY → LIMIT."],
        "solution_sql": "SELECT * FROM employees WHERE is_active = 1 ORDER BY salary DESC LIMIT 5",
        "starter_sql": "",
        "validation": {"order_sensitive": True, "allow_extra_columns": False},
        "tables": ["employees"],
    },
    {
        "id": "beg_035", "difficulty": "beginner", "category": "WHERE",
        "title": "Cheapest Electronics",
        "description": "Find the 3 least expensive products in the 'Electronics' category.",
        "hints": ["Filter by category first, then sort by price ascending, then limit."],
        "solution_sql": "SELECT * FROM products WHERE category = 'Electronics' ORDER BY price ASC LIMIT 3",
        "starter_sql": "",
        "validation": {"order_sensitive": True, "allow_extra_columns": False},
        "tables": ["products"],
    },
    {
        "id": "beg_036", "difficulty": "beginner", "category": "WHERE",
        "title": "Recent Delivered Orders",
        "description": "Find the 10 most recent orders with status 'delivered'.",
        "hints": ["Filter on status, then sort by order_date descending, then LIMIT 10."],
        "solution_sql": "SELECT * FROM orders WHERE status = 'delivered' ORDER BY order_date DESC LIMIT 10",
        "starter_sql": "",
        "validation": {"order_sensitive": True, "allow_extra_columns": False},
        "tables": ["orders"],
    },
    # ── Aliases ─────────────────────────────────────────────────────────────────
    {
        "id": "beg_037", "difficulty": "beginner", "category": "SELECT",
        "title": "Column Aliases",
        "description": "Retrieve employee first_name and last_name, but label them 'First Name' and 'Last Name' in the output.",
        "hints": ["AS lets you rename a column in the result.", "Use quotes if the alias has spaces: AS 'First Name'"],
        "solution_sql": "SELECT first_name AS 'First Name', last_name AS 'Last Name' FROM employees",
        "starter_sql": "",
        "validation": {"order_sensitive": False, "allow_extra_columns": False},
        "tables": ["employees"],
    },
    {
        "id": "beg_038", "difficulty": "beginner", "category": "SELECT",
        "title": "Price in Dollars",
        "description": "Select the product name and price, labeling the price column as 'price_usd'.",
        "hints": ["Use AS to alias the column name."],
        "solution_sql": "SELECT name, price AS price_usd FROM products",
        "starter_sql": "",
        "validation": {"order_sensitive": False, "allow_extra_columns": False},
        "tables": ["products"],
    },
    # ── Simple math ─────────────────────────────────────────────────────────────
    {
        "id": "beg_039", "difficulty": "beginner", "category": "SELECT",
        "title": "Annual Salary",
        "description": "Retrieve each employee's first_name, last_name, and their salary multiplied by 12 as 'annual_salary'.",
        "hints": ["You can do math directly in SELECT: salary * 12", "Use AS to label the result."],
        "solution_sql": "SELECT first_name, last_name, salary * 12 AS annual_salary FROM employees",
        "starter_sql": "",
        "validation": {"order_sensitive": False, "allow_extra_columns": False},
        "tables": ["employees"],
    },
    {
        "id": "beg_040", "difficulty": "beginner", "category": "SELECT",
        "title": "Order Item Total",
        "description": "For each order item, retrieve the order_id, product_id, and calculate the line total (quantity * unit_price) as 'line_total'.",
        "hints": ["Multiply two columns: quantity * unit_price", "Give it an alias with AS 'line_total'"],
        "solution_sql": "SELECT order_id, product_id, quantity * unit_price AS line_total FROM order_items",
        "starter_sql": "",
        "validation": {"order_sensitive": False, "allow_extra_columns": False},
        "tables": ["order_items"],
    },
    {
        "id": "beg_041", "difficulty": "beginner", "category": "WHERE",
        "title": "Sales Reps in the West",
        "description": "Find all sales reps assigned to the 'West' region.",
        "hints": ["Filter on the region column of the sales_reps table."],
        "solution_sql": "SELECT * FROM sales_reps WHERE region = 'West'",
        "starter_sql": "",
        "validation": {"order_sensitive": False, "allow_extra_columns": False},
        "tables": ["sales_reps"],
    },
    {
        "id": "beg_042", "difficulty": "beginner", "category": "WHERE",
        "title": "Big Orders",
        "description": "Find all orders where total_amount is greater than 1000.",
        "hints": ["Compare total_amount > 1000 in your WHERE clause."],
        "solution_sql": "SELECT * FROM orders WHERE total_amount > 1000",
        "starter_sql": "",
        "validation": {"order_sensitive": False, "allow_extra_columns": False},
        "tables": ["orders"],
    },
    {
        "id": "beg_043", "difficulty": "beginner", "category": "SELECT",
        "title": "All Sales Reps",
        "description": "Retrieve every column from the sales_reps table.",
        "hints": ["SELECT * gets everything."],
        "solution_sql": "SELECT * FROM sales_reps",
        "starter_sql": "",
        "validation": {"order_sensitive": False, "allow_extra_columns": False},
        "tables": ["sales_reps"],
    },
]
