INTERMEDIATE_CHALLENGES = [
    # ── Aggregates ─────────────────────────────────────────────────────────────
    {
        "id": "int_001", "difficulty": "intermediate", "category": "Aggregates",
        "title": "Total Number of Employees",
        "description": "Count the total number of rows in the employees table.",
        "hints": ["COUNT(*) counts every row.", "No GROUP BY needed when you want a single total."],
        "solution_sql": "SELECT COUNT(*) AS total_employees FROM employees",
        "starter_sql": "SELECT\nFROM employees",
        "validation": {"order_sensitive": False, "allow_extra_columns": False},
        "tables": ["employees"],
    },
    {
        "id": "int_002", "difficulty": "intermediate", "category": "Aggregates",
        "title": "Average Salary",
        "description": "Find the average salary across all employees.",
        "hints": ["AVG() computes the average of a numeric column."],
        "solution_sql": "SELECT AVG(salary) AS avg_salary FROM employees",
        "starter_sql": "",
        "validation": {"order_sensitive": False, "allow_extra_columns": False},
        "tables": ["employees"],
    },
    {
        "id": "int_003", "difficulty": "intermediate", "category": "Aggregates",
        "title": "Total Revenue",
        "description": "Calculate the total revenue (sum of all total_amount values) from the orders table.",
        "hints": ["SUM() adds up all values in a column."],
        "solution_sql": "SELECT SUM(total_amount) AS total_revenue FROM orders",
        "starter_sql": "",
        "validation": {"order_sensitive": False, "allow_extra_columns": False},
        "tables": ["orders"],
    },
    {
        "id": "int_004", "difficulty": "intermediate", "category": "Aggregates",
        "title": "Min and Max Product Price",
        "description": "Find the lowest and highest product prices in a single query. Label them min_price and max_price.",
        "hints": ["You can use multiple aggregate functions in one SELECT."],
        "solution_sql": "SELECT MIN(price) AS min_price, MAX(price) AS max_price FROM products",
        "starter_sql": "",
        "validation": {"order_sensitive": False, "allow_extra_columns": False},
        "tables": ["products"],
    },
    {
        "id": "int_005", "difficulty": "intermediate", "category": "Aggregates",
        "title": "Count Delivered Orders",
        "description": "Count how many orders have a status of 'delivered'.",
        "hints": ["Combine COUNT(*) with a WHERE clause."],
        "solution_sql": "SELECT COUNT(*) AS delivered_count FROM orders WHERE status = 'delivered'",
        "starter_sql": "",
        "validation": {"order_sensitive": False, "allow_extra_columns": False},
        "tables": ["orders"],
    },
    {
        "id": "int_006", "difficulty": "intermediate", "category": "Aggregates",
        "title": "Total Stock Value",
        "description": "Calculate the total inventory value: sum of (price * stock_quantity) across all products. Label it total_inventory_value.",
        "hints": ["You can do math inside SUM(): SUM(price * stock_quantity)"],
        "solution_sql": "SELECT SUM(price * stock_quantity) AS total_inventory_value FROM products",
        "starter_sql": "",
        "validation": {"order_sensitive": False, "allow_extra_columns": False},
        "tables": ["products"],
    },
    # ── GROUP BY ───────────────────────────────────────────────────────────────
    {
        "id": "int_007", "difficulty": "intermediate", "category": "GROUP BY",
        "title": "Employees Per Department",
        "description": "Count the number of employees in each department. Show dept_id and employee_count.",
        "hints": ["GROUP BY groups rows sharing the same value.", "COUNT(*) then counts within each group."],
        "solution_sql": "SELECT dept_id, COUNT(*) AS employee_count FROM employees GROUP BY dept_id",
        "starter_sql": "SELECT dept_id,\nFROM employees\nGROUP BY",
        "validation": {"order_sensitive": False, "allow_extra_columns": False},
        "tables": ["employees"],
    },
    {
        "id": "int_008", "difficulty": "intermediate", "category": "GROUP BY",
        "title": "Average Salary by Department",
        "description": "Calculate the average salary for each department. Show dept_id and avg_salary.",
        "hints": ["GROUP BY dept_id, then AVG(salary)."],
        "solution_sql": "SELECT dept_id, AVG(salary) AS avg_salary FROM employees GROUP BY dept_id",
        "starter_sql": "",
        "validation": {"order_sensitive": False, "allow_extra_columns": False},
        "tables": ["employees"],
    },
    {
        "id": "int_009", "difficulty": "intermediate", "category": "GROUP BY",
        "title": "Orders Per Customer",
        "description": "Count how many orders each customer has placed. Show customer_id and order_count, sorted by order_count descending.",
        "hints": ["GROUP BY customer_id.", "Sort with ORDER BY order_count DESC after GROUP BY."],
        "solution_sql": "SELECT customer_id, COUNT(*) AS order_count FROM orders GROUP BY customer_id ORDER BY order_count DESC",
        "starter_sql": "",
        "validation": {"order_sensitive": True, "allow_extra_columns": False},
        "tables": ["orders"],
    },
    {
        "id": "int_010", "difficulty": "intermediate", "category": "GROUP BY",
        "title": "Total Sales by Status",
        "description": "For each order status, calculate the total revenue. Show status and total_revenue.",
        "hints": ["GROUP BY status, then SUM(total_amount)."],
        "solution_sql": "SELECT status, SUM(total_amount) AS total_revenue FROM orders GROUP BY status",
        "starter_sql": "",
        "validation": {"order_sensitive": False, "allow_extra_columns": False},
        "tables": ["orders"],
    },
    {
        "id": "int_011", "difficulty": "intermediate", "category": "GROUP BY",
        "title": "Products Per Category",
        "description": "Count the number of products in each category. Show category and product_count.",
        "hints": ["GROUP BY category, then COUNT(*)."],
        "solution_sql": "SELECT category, COUNT(*) AS product_count FROM products GROUP BY category",
        "starter_sql": "",
        "validation": {"order_sensitive": False, "allow_extra_columns": False},
        "tables": ["products"],
    },
    {
        "id": "int_012", "difficulty": "intermediate", "category": "GROUP BY",
        "title": "Revenue by Region",
        "description": "Calculate total ytd_sales for each region from the sales_reps table. Show region and total_ytd_sales.",
        "hints": ["GROUP BY region, SUM(ytd_sales)."],
        "solution_sql": "SELECT region, SUM(ytd_sales) AS total_ytd_sales FROM sales_reps GROUP BY region",
        "starter_sql": "",
        "validation": {"order_sensitive": False, "allow_extra_columns": False},
        "tables": ["sales_reps"],
    },
    # ── HAVING ─────────────────────────────────────────────────────────────────
    {
        "id": "int_013", "difficulty": "intermediate", "category": "HAVING",
        "title": "Busy Departments",
        "description": "Find departments that have more than 10 employees. Show dept_id and employee_count.",
        "hints": ["HAVING filters groups after GROUP BY.", "Don't use WHERE to filter on COUNT — use HAVING."],
        "solution_sql": "SELECT dept_id, COUNT(*) AS employee_count FROM employees GROUP BY dept_id HAVING COUNT(*) > 10",
        "starter_sql": "SELECT dept_id, COUNT(*) AS employee_count\nFROM employees\nGROUP BY dept_id\nHAVING",
        "validation": {"order_sensitive": False, "allow_extra_columns": False},
        "tables": ["employees"],
    },
    {
        "id": "int_014", "difficulty": "intermediate", "category": "HAVING",
        "title": "High-Value Customers",
        "description": "Find customers who have placed 5 or more orders. Show customer_id and order_count.",
        "hints": ["GROUP BY customer_id, COUNT(*) >= 5 in HAVING."],
        "solution_sql": "SELECT customer_id, COUNT(*) AS order_count FROM orders GROUP BY customer_id HAVING COUNT(*) >= 5",
        "starter_sql": "",
        "validation": {"order_sensitive": False, "allow_extra_columns": False},
        "tables": ["orders"],
    },
    {
        "id": "int_015", "difficulty": "intermediate", "category": "HAVING",
        "title": "Expensive Categories",
        "description": "Find product categories where the average price is above 200. Show category and avg_price.",
        "hints": ["HAVING AVG(price) > 200 filters after grouping."],
        "solution_sql": "SELECT category, AVG(price) AS avg_price FROM products GROUP BY category HAVING AVG(price) > 200",
        "starter_sql": "",
        "validation": {"order_sensitive": False, "allow_extra_columns": False},
        "tables": ["products"],
    },
    # ── INNER JOIN ─────────────────────────────────────────────────────────────
    {
        "id": "int_016", "difficulty": "intermediate", "category": "JOIN",
        "title": "Employees With Department Names",
        "description": "For each employee, show their first_name, last_name, and department name. Use a JOIN.",
        "hints": [
            "JOIN departments d ON e.dept_id = d.id",
            "Give each table an alias: employees e, departments d",
        ],
        "solution_sql": "SELECT e.first_name, e.last_name, d.name AS department FROM employees e JOIN departments d ON e.dept_id = d.id",
        "starter_sql": "SELECT e.first_name, e.last_name, d.name AS department\nFROM employees e\nJOIN departments d ON",
        "validation": {"order_sensitive": False, "allow_extra_columns": False},
        "tables": ["employees", "departments"],
    },
    {
        "id": "int_017", "difficulty": "intermediate", "category": "JOIN",
        "title": "Orders With Customer Names",
        "description": "Show each order's id, order_date, total_amount, and the customer's first_name and last_name.",
        "hints": [
            "JOIN customers c ON o.customer_id = c.id",
            "FROM orders o JOIN customers c ...",
        ],
        "solution_sql": "SELECT o.id, o.order_date, o.total_amount, c.first_name, c.last_name FROM orders o JOIN customers c ON o.customer_id = c.id",
        "starter_sql": "",
        "validation": {"order_sensitive": False, "allow_extra_columns": False},
        "tables": ["orders", "customers"],
    },
    {
        "id": "int_018", "difficulty": "intermediate", "category": "JOIN",
        "title": "Order Items With Product Names",
        "description": "For each order item, show the order_id, quantity, unit_price, and the product name.",
        "hints": ["JOIN products p ON oi.product_id = p.id"],
        "solution_sql": "SELECT oi.order_id, oi.quantity, oi.unit_price, p.name AS product_name FROM order_items oi JOIN products p ON oi.product_id = p.id",
        "starter_sql": "",
        "validation": {"order_sensitive": False, "allow_extra_columns": False},
        "tables": ["order_items", "products"],
    },
    {
        "id": "int_019", "difficulty": "intermediate", "category": "JOIN",
        "title": "Sales Reps With Employee Names",
        "description": "Show each sales rep's region, commission_rate, and the employee's first_name and last_name.",
        "hints": ["JOIN employees e ON sr.employee_id = e.id"],
        "solution_sql": "SELECT sr.region, sr.commission_rate, e.first_name, e.last_name FROM sales_reps sr JOIN employees e ON sr.employee_id = e.id",
        "starter_sql": "",
        "validation": {"order_sensitive": False, "allow_extra_columns": False},
        "tables": ["sales_reps", "employees"],
    },
    {
        "id": "int_020", "difficulty": "intermediate", "category": "JOIN",
        "title": "Three-Table Join",
        "description": "Show each order item's product name, the customer's last_name, and the quantity ordered.",
        "hints": [
            "Chain two JOINs: order_items → orders → customers and order_items → products.",
            "FROM order_items oi JOIN orders o ON oi.order_id = o.id JOIN customers c ON o.customer_id = c.id JOIN products p ON oi.product_id = p.id",
        ],
        "solution_sql": "SELECT p.name AS product_name, c.last_name AS customer_last_name, oi.quantity FROM order_items oi JOIN orders o ON oi.order_id = o.id JOIN customers c ON o.customer_id = c.id JOIN products p ON oi.product_id = p.id",
        "starter_sql": "",
        "validation": {"order_sensitive": False, "allow_extra_columns": False},
        "tables": ["order_items", "orders", "customers", "products"],
    },
    # ── LEFT JOIN ──────────────────────────────────────────────────────────────
    {
        "id": "int_021", "difficulty": "intermediate", "category": "JOIN",
        "title": "Customers Without Orders",
        "description": "Find all customers who have never placed an order. Show customer first_name, last_name.",
        "hints": [
            "Use LEFT JOIN from customers to orders.",
            "When there's no matching order, o.id will be NULL.",
            "Filter WHERE o.id IS NULL.",
        ],
        "solution_sql": "SELECT c.first_name, c.last_name FROM customers c LEFT JOIN orders o ON c.id = o.customer_id WHERE o.id IS NULL",
        "starter_sql": "SELECT c.first_name, c.last_name\nFROM customers c\nLEFT JOIN orders o ON c.id = o.customer_id\nWHERE",
        "validation": {"order_sensitive": False, "allow_extra_columns": False},
        "tables": ["customers", "orders"],
    },
    {
        "id": "int_022", "difficulty": "intermediate", "category": "JOIN",
        "title": "All Employees, Even Unassigned",
        "description": "List all employees with their department name. Employees with no department should still appear (show NULL for department name).",
        "hints": ["LEFT JOIN keeps all rows from the left table.", "Unmatched rows in the right table become NULL."],
        "solution_sql": "SELECT e.first_name, e.last_name, d.name AS department FROM employees e LEFT JOIN departments d ON e.dept_id = d.id",
        "starter_sql": "",
        "validation": {"order_sensitive": False, "allow_extra_columns": False},
        "tables": ["employees", "departments"],
    },
    # ── Subqueries ─────────────────────────────────────────────────────────────
    {
        "id": "int_023", "difficulty": "intermediate", "category": "Subqueries",
        "title": "Above Average Salary",
        "description": "Find all employees whose salary is above the company average. Show first_name, last_name, salary.",
        "hints": [
            "Use a subquery in WHERE: WHERE salary > (SELECT AVG(salary) FROM employees)",
            "The inner query runs first and returns a single number.",
        ],
        "solution_sql": "SELECT first_name, last_name, salary FROM employees WHERE salary > (SELECT AVG(salary) FROM employees)",
        "starter_sql": "SELECT first_name, last_name, salary\nFROM employees\nWHERE salary > (SELECT",
        "validation": {"order_sensitive": False, "allow_extra_columns": False},
        "tables": ["employees"],
    },
    {
        "id": "int_024", "difficulty": "intermediate", "category": "Subqueries",
        "title": "Customers Who Have Ordered",
        "description": "Find customers who have placed at least one order, using a subquery (not a JOIN). Show first_name and last_name.",
        "hints": [
            "WHERE id IN (SELECT customer_id FROM orders)",
            "The subquery returns a list of customer_ids who have orders.",
        ],
        "solution_sql": "SELECT first_name, last_name FROM customers WHERE id IN (SELECT customer_id FROM orders)",
        "starter_sql": "",
        "validation": {"order_sensitive": False, "allow_extra_columns": False},
        "tables": ["customers", "orders"],
    },
    {
        "id": "int_025", "difficulty": "intermediate", "category": "Subqueries",
        "title": "Most Expensive Product",
        "description": "Retrieve the full row for the most expensive product.",
        "hints": ["WHERE price = (SELECT MAX(price) FROM products)"],
        "solution_sql": "SELECT * FROM products WHERE price = (SELECT MAX(price) FROM products)",
        "starter_sql": "",
        "validation": {"order_sensitive": False, "allow_extra_columns": False},
        "tables": ["products"],
    },
    {
        "id": "int_026", "difficulty": "intermediate", "category": "Subqueries",
        "title": "Departments Above Budget Average",
        "description": "Find all departments whose budget is above the average department budget. Show name and budget.",
        "hints": ["WHERE budget > (SELECT AVG(budget) FROM departments)"],
        "solution_sql": "SELECT name, budget FROM departments WHERE budget > (SELECT AVG(budget) FROM departments)",
        "starter_sql": "",
        "validation": {"order_sensitive": False, "allow_extra_columns": False},
        "tables": ["departments"],
    },
    # ── CASE WHEN ──────────────────────────────────────────────────────────────
    {
        "id": "int_027", "difficulty": "intermediate", "category": "CASE WHEN",
        "title": "Salary Band",
        "description": "Label each employee with a salary band: 'Low' if salary < 60000, 'Mid' if 60000-100000, 'High' if above 100000. Show first_name, last_name, salary, and salary_band.",
        "hints": [
            "CASE WHEN salary < 60000 THEN 'Low' WHEN salary <= 100000 THEN 'Mid' ELSE 'High' END",
            "Give the CASE expression an alias: AS salary_band",
        ],
        "solution_sql": "SELECT first_name, last_name, salary, CASE WHEN salary < 60000 THEN 'Low' WHEN salary <= 100000 THEN 'Mid' ELSE 'High' END AS salary_band FROM employees",
        "starter_sql": "SELECT first_name, last_name, salary,\n  CASE\n    WHEN salary < 60000 THEN 'Low'\n    WHEN salary <= 100000 THEN 'Mid'\n    ELSE 'High'\n  END AS salary_band\nFROM employees",
        "validation": {"order_sensitive": False, "allow_extra_columns": False},
        "tables": ["employees"],
    },
    {
        "id": "int_028", "difficulty": "intermediate", "category": "CASE WHEN",
        "title": "Order Status Label",
        "description": "For each order, show the order id and a 'flag' column: 'Complete' if status is 'delivered', 'In Progress' if 'processing' or 'shipped', 'Not Started' if 'pending', and 'Void' for cancelled.",
        "hints": ["Use CASE WHEN with multiple WHEN branches."],
        "solution_sql": "SELECT id, CASE WHEN status = 'delivered' THEN 'Complete' WHEN status IN ('processing', 'shipped') THEN 'In Progress' WHEN status = 'pending' THEN 'Not Started' ELSE 'Void' END AS flag FROM orders",
        "starter_sql": "",
        "validation": {"order_sensitive": False, "allow_extra_columns": False},
        "tables": ["orders"],
    },
    {
        "id": "int_029", "difficulty": "intermediate", "category": "CASE WHEN",
        "title": "Stock Alert",
        "description": "For each product, show name, stock_quantity, and a 'stock_status': 'Out of Stock' if 0, 'Low' if 1-20, 'OK' otherwise.",
        "hints": ["CASE WHEN stock_quantity = 0 THEN ... WHEN stock_quantity <= 20 THEN ... ELSE ... END"],
        "solution_sql": "SELECT name, stock_quantity, CASE WHEN stock_quantity = 0 THEN 'Out of Stock' WHEN stock_quantity <= 20 THEN 'Low' ELSE 'OK' END AS stock_status FROM products",
        "starter_sql": "",
        "validation": {"order_sensitive": False, "allow_extra_columns": False},
        "tables": ["products"],
    },
    # ── String Functions ────────────────────────────────────────────────────────
    {
        "id": "int_030", "difficulty": "intermediate", "category": "String Functions",
        "title": "Full Name Column",
        "description": "Create a single column 'full_name' that combines first_name and last_name with a space in between, for all employees.",
        "hints": ["Use || to concatenate strings in SQLite: first_name || ' ' || last_name"],
        "solution_sql": "SELECT first_name || ' ' || last_name AS full_name FROM employees",
        "starter_sql": "",
        "validation": {"order_sensitive": False, "allow_extra_columns": False},
        "tables": ["employees"],
    },
    {
        "id": "int_031", "difficulty": "intermediate", "category": "String Functions",
        "title": "Uppercase Department Names",
        "description": "Retrieve all department names converted to uppercase.",
        "hints": ["UPPER() converts a string to uppercase."],
        "solution_sql": "SELECT UPPER(name) AS name FROM departments",
        "starter_sql": "",
        "validation": {"order_sensitive": False, "allow_extra_columns": False},
        "tables": ["departments"],
    },
    {
        "id": "int_032", "difficulty": "intermediate", "category": "String Functions",
        "title": "Email Domain",
        "description": "Extract just the domain portion of each customer's email (everything after the @). Label it 'email_domain'.",
        "hints": [
            "SUBSTR(email, INSTR(email, '@') + 1) extracts from after the @ to the end.",
            "INSTR(email, '@') returns the position of @.",
        ],
        "solution_sql": "SELECT email, SUBSTR(email, INSTR(email, '@') + 1) AS email_domain FROM customers",
        "starter_sql": "",
        "validation": {"order_sensitive": False, "allow_extra_columns": False},
        "tables": ["customers"],
    },
    {
        "id": "int_033", "difficulty": "intermediate", "category": "String Functions",
        "title": "Product Name Length",
        "description": "Show each product's name and the character length of the name as 'name_length', sorted by name_length descending.",
        "hints": ["LENGTH() returns the number of characters in a string."],
        "solution_sql": "SELECT name, LENGTH(name) AS name_length FROM products ORDER BY name_length DESC",
        "starter_sql": "",
        "validation": {"order_sensitive": True, "allow_extra_columns": False},
        "tables": ["products"],
    },
    # ── Date Functions ──────────────────────────────────────────────────────────
    {
        "id": "int_034", "difficulty": "intermediate", "category": "Date Functions",
        "title": "Orders in 2023",
        "description": "Find all orders placed in the year 2023.",
        "hints": ["STRFTIME('%Y', order_date) extracts the year.", "WHERE STRFTIME('%Y', order_date) = '2023'"],
        "solution_sql": "SELECT * FROM orders WHERE STRFTIME('%Y', order_date) = '2023'",
        "starter_sql": "SELECT * FROM orders\nWHERE STRFTIME('%Y', order_date) =",
        "validation": {"order_sensitive": False, "allow_extra_columns": False},
        "tables": ["orders"],
    },
    {
        "id": "int_035", "difficulty": "intermediate", "category": "Date Functions",
        "title": "Orders Per Month",
        "description": "Count how many orders were placed each month (all years). Show year_month (e.g. '2023-01') and order_count, sorted chronologically.",
        "hints": ["STRFTIME('%Y-%m', order_date) groups by year and month.", "ORDER BY year_month ASC."],
        "solution_sql": "SELECT STRFTIME('%Y-%m', order_date) AS year_month, COUNT(*) AS order_count FROM orders GROUP BY year_month ORDER BY year_month ASC",
        "starter_sql": "",
        "validation": {"order_sensitive": True, "allow_extra_columns": False},
        "tables": ["orders"],
    },
    {
        "id": "int_036", "difficulty": "intermediate", "category": "Date Functions",
        "title": "Employee Tenure",
        "description": "For each employee, calculate how many days they have been employed (from hire_date to today). Show first_name, last_name, hire_date, and days_employed.",
        "hints": [
            "JULIANDAY('now') - JULIANDAY(hire_date) gives days as a float.",
            "CAST(... AS INTEGER) rounds it down.",
        ],
        "solution_sql": "SELECT first_name, last_name, hire_date, CAST(JULIANDAY('now') - JULIANDAY(hire_date) AS INTEGER) AS days_employed FROM employees",
        "starter_sql": "",
        "validation": {"order_sensitive": False, "allow_extra_columns": True},
        "tables": ["employees"],
    },
    {
        "id": "int_037", "difficulty": "intermediate", "category": "Date Functions",
        "title": "Customers Who Registered in 2022",
        "description": "Find all customers who registered during the year 2022.",
        "hints": ["Filter with STRFTIME('%Y', registration_date) = '2022'"],
        "solution_sql": "SELECT * FROM customers WHERE STRFTIME('%Y', registration_date) = '2022'",
        "starter_sql": "",
        "validation": {"order_sensitive": False, "allow_extra_columns": False},
        "tables": ["customers"],
    },
    # ── GROUP BY + JOIN ────────────────────────────────────────────────────────
    {
        "id": "int_038", "difficulty": "intermediate", "category": "GROUP BY",
        "title": "Revenue by Department",
        "description": "Show each department's name and the total salary cost (SUM of salaries). JOIN departments to employees.",
        "hints": [
            "JOIN employees to departments, then GROUP BY department name.",
            "SUM(e.salary) after the GROUP BY gives total payroll per dept.",
        ],
        "solution_sql": "SELECT d.name AS department, SUM(e.salary) AS total_salary FROM employees e JOIN departments d ON e.dept_id = d.id GROUP BY d.name",
        "starter_sql": "",
        "validation": {"order_sensitive": False, "allow_extra_columns": False},
        "tables": ["employees", "departments"],
    },
    {
        "id": "int_039", "difficulty": "intermediate", "category": "GROUP BY",
        "title": "Orders Per Customer (With Name)",
        "description": "Show each customer's first_name, last_name, and how many orders they've placed as order_count. Only show customers who have placed at least one order.",
        "hints": [
            "JOIN customers and orders, GROUP BY customer name.",
            "INNER JOIN only returns rows that have a match in both tables.",
        ],
        "solution_sql": "SELECT c.first_name, c.last_name, COUNT(o.id) AS order_count FROM customers c JOIN orders o ON c.id = o.customer_id GROUP BY c.id, c.first_name, c.last_name ORDER BY order_count DESC",
        "starter_sql": "",
        "validation": {"order_sensitive": True, "allow_extra_columns": False},
        "tables": ["customers", "orders"],
    },
    {
        "id": "int_040", "difficulty": "intermediate", "category": "HAVING",
        "title": "High-Revenue Departments",
        "description": "Find departments where the total salary cost exceeds 1,000,000. Show department name and total_salary.",
        "hints": [
            "JOIN employees to departments, GROUP BY dept name.",
            "HAVING SUM(e.salary) > 1000000 filters after grouping.",
        ],
        "solution_sql": "SELECT d.name AS department, SUM(e.salary) AS total_salary FROM employees e JOIN departments d ON e.dept_id = d.id GROUP BY d.name HAVING SUM(e.salary) > 1000000",
        "starter_sql": "",
        "validation": {"order_sensitive": False, "allow_extra_columns": False},
        "tables": ["employees", "departments"],
    },
    {
        "id": "int_041", "difficulty": "intermediate", "category": "Subqueries",
        "title": "Employees in High-Budget Departments",
        "description": "Find employees who work in departments with a budget greater than 1,500,000. Show first_name, last_name.",
        "hints": [
            "WHERE dept_id IN (SELECT id FROM departments WHERE budget > 1500000)",
        ],
        "solution_sql": "SELECT first_name, last_name FROM employees WHERE dept_id IN (SELECT id FROM departments WHERE budget > 1500000)",
        "starter_sql": "",
        "validation": {"order_sensitive": False, "allow_extra_columns": False},
        "tables": ["employees", "departments"],
    },
    {
        "id": "int_042", "difficulty": "intermediate", "category": "JOIN",
        "title": "Sales Rep Commission Earned",
        "description": "For each sales rep, show their employee first_name, last_name, region, and calculated commission (ytd_sales * commission_rate) as commission_earned.",
        "hints": [
            "JOIN sales_reps to employees.",
            "sr.ytd_sales * sr.commission_rate gives the commission.",
        ],
        "solution_sql": "SELECT e.first_name, e.last_name, sr.region, ROUND(sr.ytd_sales * sr.commission_rate, 2) AS commission_earned FROM sales_reps sr JOIN employees e ON sr.employee_id = e.id",
        "starter_sql": "",
        "validation": {"order_sensitive": False, "allow_extra_columns": False},
        "tables": ["sales_reps", "employees"],
    },
]
