ANALYST_CHALLENGES = [
    {
        "id": "ana_001", "difficulty": "intermediate", "category": "Random Analyst",
        "title": "Find Duplicate Customer Emails",
        "scenario": "The data team suspects some customers registered twice using the same email. Your job: find any email addresses that appear more than once in the customers table.",
        "description": "Find all email addresses in the customers table that appear more than once. Show email and count (as occurrences), sorted by occurrences descending.",
        "hints": [
            "GROUP BY email, then HAVING COUNT(*) > 1.",
        ],
        "solution_sql": "SELECT email, COUNT(*) AS occurrences FROM customers GROUP BY email HAVING COUNT(*) > 1 ORDER BY occurrences DESC",
        "starter_sql": "",
        "validation": {"order_sensitive": True, "allow_extra_columns": False},
        "tables": ["customers"],
    },
    {
        "id": "ana_002", "difficulty": "intermediate", "category": "Random Analyst",
        "title": "Month-Over-Month Revenue",
        "scenario": "The VP of Sales wants to know how revenue has trended month by month. Calculate total revenue grouped by year-month.",
        "description": "Calculate total order revenue per month. Show year_month (formatted as 'YYYY-MM') and monthly_revenue, sorted chronologically.",
        "hints": [
            "STRFTIME('%Y-%m', order_date) groups by month.",
            "SUM(total_amount) gives revenue per month.",
        ],
        "solution_sql": "SELECT STRFTIME('%Y-%m', order_date) AS year_month, SUM(total_amount) AS monthly_revenue FROM orders GROUP BY year_month ORDER BY year_month ASC",
        "starter_sql": "",
        "validation": {"order_sensitive": True, "allow_extra_columns": False},
        "tables": ["orders"],
    },
    {
        "id": "ana_003", "difficulty": "advanced", "category": "Random Analyst",
        "title": "Customer Lifetime Value",
        "scenario": "Marketing wants to rank customers by their total spend to identify the most valuable accounts.",
        "description": "Calculate each customer's total spend (sum of all their order total_amounts). Show customer_id and lifetime_value, sorted by lifetime_value descending.",
        "hints": [
            "GROUP BY customer_id, SUM(total_amount) AS lifetime_value.",
        ],
        "solution_sql": "SELECT customer_id, SUM(total_amount) AS lifetime_value FROM orders GROUP BY customer_id ORDER BY lifetime_value DESC",
        "starter_sql": "",
        "validation": {"order_sensitive": True, "allow_extra_columns": False},
        "tables": ["orders"],
    },
    {
        "id": "ana_004", "difficulty": "advanced", "category": "Random Analyst",
        "title": "Products Never Ordered",
        "scenario": "The inventory team wants to know which products have never been purchased so they can decide whether to discontinue them.",
        "description": "Find all products that have never appeared in any order. Show product name and category.",
        "hints": [
            "LEFT JOIN order_items to products, then filter WHERE order_items.id IS NULL.",
            "Or use NOT IN / NOT EXISTS with a subquery.",
        ],
        "solution_sql": "SELECT p.name, p.category FROM products p LEFT JOIN order_items oi ON p.id = oi.product_id WHERE oi.id IS NULL",
        "starter_sql": "",
        "validation": {"order_sensitive": False, "allow_extra_columns": False},
        "tables": ["products", "order_items"],
    },
    {
        "id": "ana_005", "difficulty": "advanced", "category": "Random Analyst",
        "title": "Top 3 Products by Revenue",
        "scenario": "The product team wants to know which products are driving the most revenue to focus marketing efforts.",
        "description": "Calculate total revenue per product (SUM of quantity * unit_price from order_items), join to get the product name, and return the top 3. Show product name and total_revenue.",
        "hints": [
            "SUM(oi.quantity * oi.unit_price) grouped by product_id.",
            "JOIN products for the name, then ORDER BY revenue DESC LIMIT 3.",
        ],
        "solution_sql": "SELECT p.name, SUM(oi.quantity * oi.unit_price) AS total_revenue FROM order_items oi JOIN products p ON oi.product_id = p.id GROUP BY p.id, p.name ORDER BY total_revenue DESC LIMIT 3",
        "starter_sql": "",
        "validation": {"order_sensitive": True, "allow_extra_columns": False},
        "tables": ["order_items", "products"],
    },
    {
        "id": "ana_006", "difficulty": "advanced", "category": "Random Analyst",
        "title": "Salary Above Department Average",
        "scenario": "HR wants to identify employees who may be outliers — specifically those earning more than their department's average.",
        "description": "Find employees whose salary exceeds the average salary in their own department. Show first_name, last_name, dept_id, and salary.",
        "hints": [
            "Use a correlated subquery or CTE to get each dept's average.",
            "WHERE salary > (SELECT AVG(salary) FROM employees e2 WHERE e2.dept_id = e.dept_id)",
        ],
        "solution_sql": "SELECT first_name, last_name, dept_id, salary FROM employees e WHERE salary > (SELECT AVG(salary) FROM employees e2 WHERE e2.dept_id = e.dept_id)",
        "starter_sql": "",
        "validation": {"order_sensitive": False, "allow_extra_columns": False},
        "tables": ["employees"],
    },
    {
        "id": "ana_007", "difficulty": "advanced", "category": "Random Analyst",
        "title": "Average Days Between Orders",
        "scenario": "The retention team wants to understand customer purchasing frequency. Find the average number of days between a customer's consecutive orders.",
        "description": "For each customer with more than one order, calculate the average gap in days between consecutive orders. Show customer_id and avg_days_between_orders, sorted by avg_days_between_orders ascending.",
        "hints": [
            "Use LAG(order_date) to get the previous order date.",
            "JULIANDAY(order_date) - JULIANDAY(prev_date) gives days.",
            "Wrap in a CTE, then AVG the gaps per customer.",
        ],
        "solution_sql": "WITH ordered AS (SELECT customer_id, order_date, LAG(order_date) OVER (PARTITION BY customer_id ORDER BY order_date) AS prev_date FROM orders), gaps AS (SELECT customer_id, JULIANDAY(order_date) - JULIANDAY(prev_date) AS gap_days FROM ordered WHERE prev_date IS NOT NULL) SELECT customer_id, ROUND(AVG(gap_days), 1) AS avg_days_between_orders FROM gaps GROUP BY customer_id ORDER BY avg_days_between_orders ASC",
        "starter_sql": "",
        "validation": {"order_sensitive": True, "allow_extra_columns": False},
        "tables": ["orders"],
    },
    {
        "id": "ana_008", "difficulty": "advanced", "category": "Random Analyst",
        "title": "Cohort by Registration Month",
        "scenario": "The growth team wants to see how many customers signed up each month to track user acquisition trends.",
        "description": "Count how many customers registered each month. Show registration_month (YYYY-MM format) and customer_count, sorted chronologically.",
        "hints": [
            "STRFTIME('%Y-%m', registration_date) groups by month.",
            "COUNT(*) gives the number of signups per month.",
        ],
        "solution_sql": "SELECT STRFTIME('%Y-%m', registration_date) AS registration_month, COUNT(*) AS customer_count FROM customers GROUP BY registration_month ORDER BY registration_month ASC",
        "starter_sql": "",
        "validation": {"order_sensitive": True, "allow_extra_columns": False},
        "tables": ["customers"],
    },
    {
        "id": "ana_009", "difficulty": "intermediate", "category": "Random Analyst",
        "title": "Orders With Many Line Items",
        "description": "Find orders that contain more than 4 line items (i.e., more than 4 rows in order_items for that order_id). Show order_id and item_count.",
        "hints": [
            "GROUP BY order_id in order_items, COUNT(*) as item_count.",
            "HAVING COUNT(*) > 4 filters after grouping.",
        ],
        "solution_sql": "SELECT order_id, COUNT(*) AS item_count FROM order_items GROUP BY order_id HAVING COUNT(*) > 4 ORDER BY item_count DESC",
        "starter_sql": "",
        "validation": {"order_sensitive": True, "allow_extra_columns": False},
        "tables": ["order_items"],
    },
    {
        "id": "ana_010", "difficulty": "advanced", "category": "Random Analyst",
        "title": "Commission Earned Per Sales Rep",
        "scenario": "Finance needs to calculate how much commission each sales rep earned this year based on their ytd_sales and commission_rate.",
        "description": "For each sales rep, calculate their commission_earned (ytd_sales * commission_rate). Show first_name, last_name, region, ytd_sales, commission_rate, and commission_earned (rounded to 2 decimals). Sort by commission_earned descending.",
        "hints": [
            "JOIN sales_reps to employees.",
            "ROUND(sr.ytd_sales * sr.commission_rate, 2) AS commission_earned",
        ],
        "solution_sql": "SELECT e.first_name, e.last_name, sr.region, sr.ytd_sales, sr.commission_rate, ROUND(sr.ytd_sales * sr.commission_rate, 2) AS commission_earned FROM sales_reps sr JOIN employees e ON sr.employee_id = e.id ORDER BY commission_earned DESC",
        "starter_sql": "",
        "validation": {"order_sensitive": True, "allow_extra_columns": False},
        "tables": ["sales_reps", "employees"],
    },
    {
        "id": "ana_011", "difficulty": "advanced", "category": "Random Analyst",
        "title": "7-Day Rolling Average Revenue",
        "scenario": "The BI team wants a smoothed revenue trend to filter out day-to-day noise.",
        "description": "For each day that has orders, calculate the 7-day rolling average of total revenue (total_amount). Show order_date and rolling_avg_revenue.",
        "hints": [
            "First aggregate SUM(total_amount) per order_date in a CTE.",
            "Then apply AVG(...) OVER (ORDER BY order_date ROWS BETWEEN 6 PRECEDING AND CURRENT ROW).",
        ],
        "solution_sql": "WITH daily AS (SELECT order_date, SUM(total_amount) AS daily_revenue FROM orders GROUP BY order_date) SELECT order_date, ROUND(AVG(daily_revenue) OVER (ORDER BY order_date ROWS BETWEEN 6 PRECEDING AND CURRENT ROW), 2) AS rolling_avg_revenue FROM daily ORDER BY order_date",
        "starter_sql": "",
        "validation": {"order_sensitive": True, "allow_extra_columns": False},
        "tables": ["orders"],
    },
    {
        "id": "ana_012", "difficulty": "advanced", "category": "Random Analyst",
        "title": "Top 10% Salary Earners",
        "scenario": "Compensation team wants to identify the top earners company-wide for a bonus program.",
        "description": "Find employees whose salary is in the top 10% of all salaries. Show first_name, last_name, and salary, sorted by salary descending.",
        "hints": [
            "Use PERCENT_RANK() OVER (ORDER BY salary) in a CTE.",
            "Filter WHERE pct_rank >= 0.9 in the outer query.",
        ],
        "solution_sql": "WITH ranked AS (SELECT first_name, last_name, salary, PERCENT_RANK() OVER (ORDER BY salary) AS pct_rank FROM employees) SELECT first_name, last_name, salary FROM ranked WHERE pct_rank >= 0.9 ORDER BY salary DESC",
        "starter_sql": "",
        "validation": {"order_sensitive": True, "allow_extra_columns": False},
        "tables": ["employees"],
    },
    {
        "id": "ana_013", "difficulty": "advanced", "category": "Random Analyst",
        "title": "Customer Reorder Rate",
        "scenario": "The e-commerce team wants to know what percentage of customers have placed more than one order (repeat buyers).",
        "description": "Calculate: total customers, customers with more than 1 order, and the reorder_rate (repeat / total * 100, rounded to 1 decimal). Return a single row with total_customers, repeat_customers, and reorder_rate.",
        "hints": [
            "Use a CTE to count orders per customer.",
            "Then SUM(CASE WHEN order_count > 1 THEN 1 ELSE 0 END) counts repeat buyers.",
            "ROUND(...*100.0/..., 1) gives the percentage.",
        ],
        "solution_sql": "WITH counts AS (SELECT customer_id, COUNT(*) AS order_count FROM orders GROUP BY customer_id) SELECT COUNT(*) AS total_customers, SUM(CASE WHEN order_count > 1 THEN 1 ELSE 0 END) AS repeat_customers, ROUND(SUM(CASE WHEN order_count > 1 THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 1) AS reorder_rate FROM counts",
        "starter_sql": "",
        "validation": {"order_sensitive": False, "allow_extra_columns": False},
        "tables": ["orders"],
    },
    {
        "id": "ana_014", "difficulty": "intermediate", "category": "Random Analyst",
        "title": "Total Inventory Value by Category",
        "scenario": "The warehouse team needs to know the total dollar value of current stock, broken down by product category.",
        "description": "For each product category, calculate total inventory value (SUM of price * stock_quantity). Show category and inventory_value, sorted by inventory_value descending.",
        "hints": [
            "SUM(price * stock_quantity) grouped by category.",
        ],
        "solution_sql": "SELECT category, SUM(price * stock_quantity) AS inventory_value FROM products GROUP BY category ORDER BY inventory_value DESC",
        "starter_sql": "",
        "validation": {"order_sensitive": True, "allow_extra_columns": False},
        "tables": ["products"],
    },
    {
        "id": "ana_015", "difficulty": "advanced", "category": "Random Analyst",
        "title": "First Purchase Product per Customer",
        "scenario": "The marketing team wants to know what product each customer bought first to understand entry-point products.",
        "description": "For each customer, find the product name of their first order item (earliest order_date). Show customer_id and first_product.",
        "hints": [
            "Use ROW_NUMBER() OVER (PARTITION BY o.customer_id ORDER BY o.order_date) in a CTE.",
            "JOIN order_items and products, then filter rn = 1.",
        ],
        "solution_sql": "WITH first_orders AS (SELECT o.customer_id, oi.product_id, o.order_date, ROW_NUMBER() OVER (PARTITION BY o.customer_id ORDER BY o.order_date) AS rn FROM orders o JOIN order_items oi ON o.id = oi.order_id) SELECT fo.customer_id, p.name AS first_product FROM first_orders fo JOIN products p ON fo.product_id = p.id WHERE fo.rn = 1",
        "starter_sql": "",
        "validation": {"order_sensitive": False, "allow_extra_columns": False},
        "tables": ["orders", "order_items", "products"],
    },
    {
        "id": "ana_016", "difficulty": "advanced", "category": "Random Analyst",
        "title": "Manager's Team Total Salary",
        "scenario": "Finance wants to know the total compensation cost for each manager's direct team.",
        "description": "For each manager, calculate the total salary of all their direct reports. Show manager_id and team_salary_total, sorted by team_salary_total descending.",
        "hints": [
            "GROUP BY manager_id, SUM(salary) WHERE manager_id IS NOT NULL.",
        ],
        "solution_sql": "SELECT manager_id, SUM(salary) AS team_salary_total FROM employees WHERE manager_id IS NOT NULL GROUP BY manager_id ORDER BY team_salary_total DESC",
        "starter_sql": "",
        "validation": {"order_sensitive": True, "allow_extra_columns": False},
        "tables": ["employees"],
    },
    {
        "id": "ana_017", "difficulty": "advanced", "category": "Random Analyst",
        "title": "Revenue Contribution by Region",
        "scenario": "The executive team wants to see each region's share of total sales revenue.",
        "description": "For each region, calculate total ytd_sales and the percentage it represents of the overall total (as pct_of_total, rounded to 1 decimal). Show region, total_ytd_sales, and pct_of_total.",
        "hints": [
            "SUM(ytd_sales) grouped by region.",
            "Divide by (SELECT SUM(ytd_sales) FROM sales_reps) * 100.0 for the percentage.",
        ],
        "solution_sql": "SELECT region, SUM(ytd_sales) AS total_ytd_sales, ROUND(SUM(ytd_sales) * 100.0 / (SELECT SUM(ytd_sales) FROM sales_reps), 1) AS pct_of_total FROM sales_reps GROUP BY region ORDER BY total_ytd_sales DESC",
        "starter_sql": "",
        "validation": {"order_sensitive": True, "allow_extra_columns": False},
        "tables": ["sales_reps"],
    },
    {
        "id": "ana_018", "difficulty": "intermediate", "category": "Random Analyst",
        "title": "Average Order Value",
        "scenario": "The growth team needs the AOV (Average Order Value) — a key e-commerce metric.",
        "description": "Calculate the average order total_amount across all orders. Label it avg_order_value, rounded to 2 decimal places.",
        "hints": [
            "ROUND(AVG(total_amount), 2) AS avg_order_value",
        ],
        "solution_sql": "SELECT ROUND(AVG(total_amount), 2) AS avg_order_value FROM orders",
        "starter_sql": "",
        "validation": {"order_sensitive": False, "allow_extra_columns": False},
        "tables": ["orders"],
    },
    {
        "id": "ana_019", "difficulty": "advanced", "category": "Random Analyst",
        "title": "Out-of-Stock Products",
        "scenario": "The supply chain team needs an immediate list of products with zero stock so they can reorder.",
        "description": "Find all products where stock_quantity is 0. Show name, category, and price, sorted by category then name.",
        "hints": [
            "WHERE stock_quantity = 0, ORDER BY category, name.",
        ],
        "solution_sql": "SELECT name, category, price FROM products WHERE stock_quantity = 0 ORDER BY category, name",
        "starter_sql": "",
        "validation": {"order_sensitive": True, "allow_extra_columns": False},
        "tables": ["products"],
    },
    {
        "id": "ana_020", "difficulty": "advanced", "category": "Random Analyst",
        "title": "New vs Returning Customers Per Month",
        "scenario": "The marketing team wants to distinguish new customers (first order that month) from returning ones.",
        "description": "For each year-month, count new customers (customers whose first-ever order was in that month) and returning customers (all others). Show year_month, new_customers, returning_customers.",
        "hints": [
            "CTE 1: ROW_NUMBER() per customer by order_date to find each customer's first order.",
            "CTE 2: label each order row as 'new' if rn=1, else 'returning'.",
            "GROUP BY month, sum each type.",
        ],
        "solution_sql": "WITH order_seq AS (SELECT customer_id, order_date, ROW_NUMBER() OVER (PARTITION BY customer_id ORDER BY order_date) AS rn FROM orders), labeled AS (SELECT STRFTIME('%Y-%m', order_date) AS ym, CASE WHEN rn = 1 THEN 1 ELSE 0 END AS is_new FROM order_seq) SELECT ym AS year_month, SUM(is_new) AS new_customers, SUM(1 - is_new) AS returning_customers FROM labeled GROUP BY ym ORDER BY ym",
        "starter_sql": "",
        "validation": {"order_sensitive": True, "allow_extra_columns": False},
        "tables": ["orders"],
    },
    {
        "id": "ana_021", "difficulty": "intermediate", "category": "Random Analyst",
        "title": "Headcount by Department",
        "scenario": "HR needs a quick headcount report broken down by department for an all-hands slide.",
        "description": "Show each department's name and the number of employees in it. Include the department name (not just id). Sort by employee_count descending.",
        "hints": [
            "JOIN employees to departments, GROUP BY department name.",
        ],
        "solution_sql": "SELECT d.name AS department, COUNT(e.id) AS employee_count FROM departments d LEFT JOIN employees e ON d.id = e.dept_id GROUP BY d.name ORDER BY employee_count DESC",
        "starter_sql": "",
        "validation": {"order_sensitive": True, "allow_extra_columns": False},
        "tables": ["departments", "employees"],
    },
    {
        "id": "ana_022", "difficulty": "advanced", "category": "Random Analyst",
        "title": "Low Commission Rate but High Sales",
        "scenario": "Finance suspects some high-performing reps are underpaid in commissions. Find reps with ytd_sales above the average but commission_rate below the average.",
        "description": "Find sales reps whose ytd_sales is above the average ytd_sales AND whose commission_rate is below the average commission_rate. Show employee_id, region, ytd_sales, and commission_rate.",
        "hints": [
            "Use subqueries for both averages in the WHERE clause.",
        ],
        "solution_sql": "SELECT employee_id, region, ytd_sales, commission_rate FROM sales_reps WHERE ytd_sales > (SELECT AVG(ytd_sales) FROM sales_reps) AND commission_rate < (SELECT AVG(commission_rate) FROM sales_reps)",
        "starter_sql": "",
        "validation": {"order_sensitive": False, "allow_extra_columns": False},
        "tables": ["sales_reps"],
    },
    {
        "id": "ana_023", "difficulty": "advanced", "category": "Random Analyst",
        "title": "Customers by Total Tier",
        "scenario": "Finance wants to segment customers into spend tiers for targeted campaigns.",
        "description": "Classify each customer by total spend: VIP (>= 5000), Gold (>= 2000), Silver (>= 500), Bronze (< 500). Show customer_id, total_spend, and tier. Sort by total_spend descending.",
        "hints": [
            "CTE: SUM(total_amount) per customer.",
            "CASE WHEN in the outer SELECT for tier assignment.",
        ],
        "solution_sql": "WITH spend AS (SELECT customer_id, SUM(total_amount) AS total_spend FROM orders GROUP BY customer_id) SELECT customer_id, total_spend, CASE WHEN total_spend >= 5000 THEN 'VIP' WHEN total_spend >= 2000 THEN 'Gold' WHEN total_spend >= 500 THEN 'Silver' ELSE 'Bronze' END AS tier FROM spend ORDER BY total_spend DESC",
        "starter_sql": "",
        "validation": {"order_sensitive": True, "allow_extra_columns": False},
        "tables": ["orders"],
    },
    {
        "id": "ana_024", "difficulty": "intermediate", "category": "Random Analyst",
        "title": "Active vs Inactive Employee Ratio",
        "scenario": "HR wants a snapshot of workforce status.",
        "description": "Count active employees (is_active = 1) and inactive employees (is_active = 0) in a single query. Show active_count and inactive_count.",
        "hints": [
            "SUM(CASE WHEN is_active = 1 THEN 1 ELSE 0 END) AS active_count",
        ],
        "solution_sql": "SELECT SUM(CASE WHEN is_active = 1 THEN 1 ELSE 0 END) AS active_count, SUM(CASE WHEN is_active = 0 THEN 1 ELSE 0 END) AS inactive_count FROM employees",
        "starter_sql": "",
        "validation": {"order_sensitive": False, "allow_extra_columns": False},
        "tables": ["employees"],
    },
    {
        "id": "ana_025", "difficulty": "advanced", "category": "Random Analyst",
        "title": "Sales Rep Rank by Region",
        "scenario": "Regional managers want to see how their reps stack up against each other within the region.",
        "description": "Rank sales reps by ytd_sales within their region (highest = rank 1). Show region, employee_id, ytd_sales, and regional_rank. Sort by region then regional_rank.",
        "hints": [
            "RANK() OVER (PARTITION BY region ORDER BY ytd_sales DESC) AS regional_rank",
        ],
        "solution_sql": "SELECT region, employee_id, ytd_sales, RANK() OVER (PARTITION BY region ORDER BY ytd_sales DESC) AS regional_rank FROM sales_reps ORDER BY region, regional_rank",
        "starter_sql": "",
        "validation": {"order_sensitive": True, "allow_extra_columns": False},
        "tables": ["sales_reps"],
    },
]
